Fix (#44)
* fix: Check out shared repo to be able to use the relative composite action to prevent usage on internal SHA's

* fix: A checkout here potenitally overwrites dotnet-security .shared folder. Added clean false to prevent removable. This is okey as long as we are on ubuntu-latest

* chore: Allow only vestfoldfylke/shared to call this composite action

diff --git a/.github/actions/dotnet-security/action.yml b/.github/actions/dotnet-security/action.yml
--- a/.github/actions/dotnet-security/action.yml
+++ b/.github/actions/dotnet-security/action.yml
@@ -24,8 +24,18 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: Only allow use from vestfoldfylke/shared
+      if: job.workflow_repository != 'vestfoldfylke/shared'
+      shell: bash
+      run: |
+        echo "::error::This action can only be used from workflows or actions in vestfoldfylke/shared (called from: ${{ job.workflow_ref }})"
+        exit 1
+
     - name: Checkout GitHub Action
       uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
+      with:
+        clean: false
+        persist-credentials: false
 
     - name: Setup .NET ${{ inputs.dotnet_version }} Environment
       uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
